function [E] = EulerratetoBF(phi,theta,psi)
  E = [...
          1, 0, -sin(theta);...
          0, cos(phi), sin(phi)*cos(theta);...
          0, -sin(phi), cos(phi)*cos(theta)];
 
%   Edot = [...
%           0, cos(phi)*tan(theta)*phi_dot+sin(phi)*sec(theta)*sec(theta)*theta_dot, -sin(phi)*tan(theta)*phi_dot+cos(phi)*sec(theta)*sec(theta)*theta_dot;...
%           0, -sin(phi)*phi_dot, -cos(phi)*phi_dot;...
%           0, cos(phi)*tan(theta)*phi_dot+sin(phi)*sec(theta)*tan(theta)*theta_dot, -sin(phi)*tan(theta)*phi_dot+cos(phi)*sec(theta)*tan(theta)*theta_dot];
 
end