function [R] = RotationIToB(phi,theta,psi)
  R_roll = [...
          1, 0, 0;...
          0, cos(phi), sin(phi);...
          0, -sin(phi), cos(phi)];
  R_pitch = [...
          cos(theta), 0, -sin(theta);...
          0, 1, 0;...
          sin(theta), 0, cos(theta)];
  R_yaw = [...
          cos(psi), sin(psi), 0;...
          -sin(psi), cos(psi), 0;...
          0, 0, 1];
%   R_roll_dot = [...
%           0, 0, 0;...
%           0, -sin(phi)*phi_dot, cos(phi)*phi_dot;...
%           0, -cos(phi)*phi_dot, -sin(phi)*phi_dot];
%   R_pitch_dot = [...
%           -sin(theta)*theta_dot, 0, -cos(theta)*theta_dot;...
%           0, 0, 0;...
%           cos(theta)*theta_dot, 0, -sin(theta)*theta_dot];
%   R_yaw_dot = [...
%           -sin(psi)*psi_dot, cos(psi)*psi_dot, 0;...
%           -cos(psi)*psi_dot, -sin(psi)*psi_dot, 0;...
%           0, 0, 0];
  R = R_roll*R_pitch*R_yaw;
%   Rdot = R_roll_dot*R_pitch*R_yaw + R_roll*R_pitch_dot*R_yaw + R_roll*R_pitch*R_yaw_dot;
end